### ISSUE TITLE
Buttons tags does not have type=button

### ISSUE THREAD

**Issue by yanickouellet** [arqex/react-datetime#11]
All `<button>` tags do not specify a `type` attribute, which cause the page to be submitted if the picker is in a `form` tag and we change month using the arrows. Here is an exemple: http://codepen.io/anon/pen/EjeOJZ Using `<button type="button">` would fix the issue, since `button` without type are considered as submit by default. 

I can make a pull request to fix that issue in the following days.

**Comment by arqex** [comment]
Sure, I'll be glad to merge your PR.
Thanks very much

**Comment by yanickouellet** [comment]
The PR has been merged, I think this issue can be closed.
