### ISSUE TITLE
[Question] How can I make the provided css file work for the datepicker?

### ISSUE THREAD

**Issue by vizFlux** [arqex/react-datetime#132]
I am using CSSModules to import css to my components. So what I did was to copy the provided css and import it with `import styles from "./rdt.css"`. Unfortunately it doesn't work as expected. Am I missing anything here?

**Comment by arqex** [comment]
Hey @vizFlux 

Never tried CSSModules so I can't help with that. I usually load the styles using webpack's style+css loaders and work like a charm.

You can also add the tag the header of your index.html, if you are still having problems.

**Comment by vizFlux** [comment]
I am using MERN stack, it doesn't load even after having the css pasted into main.css which imported to index.js :(

**Comment by simeg** [comment]
Is this the only React component you're having this problem with?

**Comment by vizFlux** [comment]
Yes

**Comment by simeg** [comment]
Are you sure you're importing the correct file? It's not called `rdt.css` in the repo, it's called `react-datetime.css`.

Can you give an example of a React component you're using which is working out-of-the-box with CSSModules?

**Comment by arqex** [comment]
The last comment in https://github.com/YouCanBookMe/react-datetime/issues/8 suggests that we should include the styles inline. It's a great idea with one downside: we would be adding the styles everytime that the picker is included, and that can happen more than one in the same page.

On the other hand, no developer would need to add the styles manually, which makes the use of react-datetime much simpler.

Thoughs?

**Comment by simeg** [comment]
Generally I feel like we should do as most other components does it, and I've never seen a React component with inline styling. What are the benefits of having the styling inline (besides resolving this particular issue)?

**Comment by arqex** [comment]
The benefits are that you don't force the component user to load the stylesheet separatelly. Inline styles sounds somehow ugly, but if you use webpack's style loader is basically what you are doing.

The other way of not making the users load the styles separately is applying the styles directly to the tag, but that makes them really difficult to overwrite.

**Comment by simeg** [comment]
So how would a developer override the inline styling? Because inline styling has highest prio. Changing the styling in the JS feels a bit awkward, and by using external CSS you have to use `!important` to be able to overwrite inline.

**Comment by ryanhca** [comment]
I've been using "Aphrodite" and was able to write a few trivial styles in the source file in order to get the styling to do minor tweaks here and there. It has been very successful and awesome!

**Comment by arqex** [comment]
When I say "inline styles" I mean the same stylesheet in a `<style />` tag. That's easily overwritable :)

**Comment by simeg** [comment]
@arqex oohh, I see. Ok that makes more sense then. In that case I have no objections against having them inline :) I'll create an issue for it.

Let's keep this issue open for further discussions and to see that @vizFlux's problem gets resolved.

**Comment by vizFlux** [comment]
@simeg @ryanhca I am using Aphrodite in my MERN project, and it is working well in replacing the styling. For example:

```javascript
import { StyleSheet, css } from 'aphrodite';
import Datetime from 'react-datetime';

const s = StyleSheet.create({
    rdtPicker: {
        width: 1000,
    },
});

<Datetime className={css(s.rdtPicker)} />
```

However, this only get the style replacement done, but not much in getting the default stylehsheet applied. The method I used to get the `react-datetime.css` applied in my current work is declaring the class as global with postcss: 

```css
:global(.rdtPicker) {
  display: none;
  position: absolute;
  width: 250px;
  padding: 4px;
  margin-top: 1px;
  z-index: 99999 !important;
  background: #fff;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
  border: 1px solid #f9f9f9;
}
```

**Comment by simeg** [comment]
@vizFlux Glad to see you managed to fix it. It seems like a lot of work to get the styling and to be able to customize it. To me that's a sign of something being broken.

**Comment by ryanhca** [comment]
in the DatePicker.js file I import Aphrodite like this 

`var assign = require('object-assign'),
        ...
	StyleSheet = require('../aphrodite')
;`

then created the styles object at the bottom of the file 

`
module.exports = Datetime;
var styles = StyleSheet.StyleSheet.create({
	bottomInput:{
		border: 'none',
		borderBottom: '2px solid #e9e9e9',
		display: 'inline',
		fontSize: "16px",
		color: "#666666",
		width: "250px",
		lineHeight: 1,
		padding: "12px 10px 8px",
		":focus": {
			borderBottom: '2px solid #005CCF',
			fontSize: '16px',
			color: "black",
		}
	},	
})`

then pass it as a prop on className to component I wanted to change.

`children = [ DOM.input( assign({
				key: 'i',
				type:'text',
				className: StyleSheet.css(styles.bottomInput),
				onFocus: this.openCalendar,
				onChange: this.onInputChange,
				value: this.state.inputValue
			}, this.props.inputProps ))];`

might be a hack but it got the job done. Best thing about Aphrodite is that it is class attribute oriented. So Instead of being "TRUE" inline, it simply injects a stylesheet directly into the head of your project only when the component is loaded. So it's pretty darn nifty and you don't have to write a bunch of "TRUE" inline styles or worry about over inheritance problems etc..

**Comment by vizFlux** [comment]
@ryanhca Amazing! didn't expect we can use Aprodite this way. However, this approach means I do need to amend the source code in the node_modules, do I?

**Comment by ryanhca** [comment]
@vizFlux Well. you have two options. When you push your code up to a production/staging server it is going to be written in the modified files and it will remain there with your styles. BUT if you are .gitIgnoring your node_modules (Which you should be) then anyone else who works on the code base wont get them. So we actually forked and cloned the library and tweaked some things and shoved it into our codebase as a component so that we can modify it whenever we want. Luckily, I'm the only one who works front-end at my company so that make it nice! haha

**Comment by vizFlux** [comment]
@ryanhca Wow I must admit as a fresh front-end developer in React, I learned some very useful things alone in this issue. Appreciate very much of your sharing man, much enjoyed!

**Comment by kevinguard** [comment]
@vizFlux I am trying the same thing as you and am wondering if you managed to convert all CSS styles in `react-datetime.css`? Since they are too many of those, making the JSON looking style to be given to `StyleSheet` of `aphrodite` is painfully slow. I wonder if you have something decently working and are able to share? Thank you!

**Comment by kevinguard** [comment]
@ryanhca How can I pass all CSS styles specified in the CSS Style sheet in this repo one-shot to Datetime component using `aphrodite`. It looks to me a nightmare as I only wish to have something out-of-box which looks similar to the demo. Thanks.

**Comment by vizFlux** [comment]
@kevinguard I am currently still using the method I mentioned above for each of the class. I wouldn't say it is decent. Quite a dirty hack if you ask me, but as far as time is concerned, I can't complain much.

```CSS
:global(.rdtPicker) {
  display: none;
  position: absolute;
  width: 250px;
  padding: 4px;
  margin-top: 1px;
  z-index: 99999 !important;
  background: #fff;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
  border: 1px solid #f9f9f9;
}
```

Been waiting for a better workaround.

**Comment by kevinguard** [comment]
@vizFlux Appreciate your help. Do you mind I take this conversation offline and I ask you few more questions via email or so? My intention is not to make too much noise here by my naive questions (I am terribly bad with CSS). Please kindly let me know.

**Comment by vizFlux** [comment]
@kevinguard  I don't mind. You can reach me through viz.flux@gmail.com

**Comment by vaishnavi168** [comment]
react-dateTime css not working. how to use that css

**Comment by rikkit** [comment]
For what it's worth, the CSS worked for me out of the box (though I did tweak a few things). My stack is TypeScript + React + SCSS + Webpack. Pasted [the example css](https://github.com/YouCanBookMe/react-datetime/blob/master/css/react-datetime.css) into a file, then ```import "./react-datetime.css"``` in a wrapper react component I made. Weback, css-loader and style loader handle getting the css into the page, and in prod I use the extract text plugin to get one big blob of css. 

I'm not sure what MERP or Aphrodite are but it seems to me to be overcomplicating things.

**Comment by ninariccimarie** [comment]
I had the same problem and just did the same with @rikkit to solve the problem :blush:

**Comment by corelema** [comment]
I'm using React + SCSS + Webpack + CSSModules.
I don't really like to copy paste the css from the repo, as I prefer not to have to manually update it if it ever changes at the source.

So I imported it into an scss file, from the node_modules, and made it global:
```
:global {
  @import "~react-datetime/css/react-datetime";
}
```

**Comment by peisenmann** [comment]
WebPack imports CSS just fine (with the appropriate loader), so I use `import 'react-datetime/css/react-datetime.css'` I agree with definitely not pasting in the CSS and manually maintaining it.

This doesn't solve the other issue of people who are not using WebPack, though.

**Comment by arqex** [comment]
The `import` method has been added to the readme :)
