### ISSUE TITLE
Unable to get the selected date value into the redux-from when date selected

### ISSUE THREAD

**Issue by bairisuresh** [arqex/react-datetime#148]
Hi @arqex  

I am using the react-datetime with redux-form. When selecting the date the value is not available to redux-from when submitting the redux-from.

Can any one help me to resolve this please.

**Comment by simeg** [comment]
Hi @bairisuresh.

[According to the `redux-form` documentation](http://redux-form.com/6.0.0-alpha.4/docs/faq/CustomComponent.md/) custom components who wants to use `redux-form` requires access to the `value` and `onChange` attributes. `react-datetime` exposes both of those attributes as props. So you need to connect `redux-form` to `react-datetime` using those props. Does that make any sense?

**Comment by bairisuresh** [comment]
<form onSubmit={handleSubmit(this.handleFormSubmit.bind(this))}></form>
when i submit the form in the handleFormSubmit function i will get formprops (all form values as key value pair). here for the date field am getting dateTime object ({_isAMomentObject: true, _strict: true, _isUTC: false, _pf: Object, _locale: r…}) not direct date value what we have selected on the screen.

**Comment by simeg** [comment]
I think you are getting the date represented as a `moment.js` object. Can you try calling `.toDate()` on the object? [Here's some documentation about `moment.js`](http://momentjs.com/docs/#/displaying/as-javascript-date/).

**Comment by simeg** [comment]
@bairisuresh did you manage to solve this?

**Comment by grbatinic-bogdan** [comment]
If someone else was struggling with this, I had the issue of connecting redux-form to react-datetime component. The values from datetime fields were not present in submit callback. [In the redux-form docs](http://redux-form.com/6.0.0-alpha.4/docs/faq/CustomComponent.md/), it stated that value and onChange was on props object, but it was in props.input object. Code example below:

`<Field name='fieldName' component={props => <DateTime inputProps={ {name: 'salesStartDate'} } value={props.input.value} onChange={param => props.input.onChange(param)} required />} />`

This way i get my values in the submit callback.

**Comment by travismgibson** [comment]
Thank you grbatinic-bogdan after 3 days of looking it worked!!

**Comment by derekcannon** [comment]
This solution works for me. However, I am having a problem where every time the form toggles between the pristine and dirty, the popup closes. So for example, on a pristine form, if I increase the time on the popup by an hour, the form closes. If I reopen and modify it in any way, it works normally. However, if I got back to the initial date, the form becomes pristine and the popup closes.

**Comment by liro** [comment]
Still having problem described in @derekcannon post. I use latest 2.14 version of react-datetime, react 15.5.4, react-dom 15.5.0, redux-form 6.8.0. This [workaround](https://github.com/YouCanBookMe/react-datetime/issues/324#issuecomment-307047159) helped me.

**Comment by arqex** [comment]
This issue has been inactive for some time, workaround seemed to work :)
