### ISSUE TITLE
Please update react-onclickoutside dependency version

### ISSUE THREAD

**Issue by arthurfranca** [arqex/react-datetime#15]
Please update dependency react-onclikoutside to version ^0.3.1.

Current package.json says "react-onclickoutside": "^0.2.4".
A fresh react-datetime install brings along react-onclikoutside v0.2.5 which seems to have a bug.

Upon picker load, browser console says "Uncaught ReferenceError: React is not defined" cause of this line: https://github.com/Pomax/react-onclickoutside/blob/a0f29a152806944702ddd014b2a0885c714f34c7/index.js#L59

**Comment by arthurfranca** [comment]
Oh, just saw there is already a PR: #13

**Comment by arqex** [comment]
Thanks @arthurfranca it should be updated in v1.1.1
