### ISSUE TITLE
Dependency classlist-polyfill makes this library error serverside

### ISSUE THREAD

**Issue by matthemsteger** [arqex/react-datetime#16]
When you try to use this serverside (for example when doing an isomorphic app), you get an error ..

> <path>/node_modules\react-datetime\node_modules\classlist-polyfill\src\index.js:18
> if ("document" in window.self) {
>                   ^
> ReferenceError: window is not defined

I looked over the source and I am a bit confused why this is included? It appears not to be used at all (no reference to .classList) for any of the code in this particular library.

**Comment by arqex** [comment]
HI @matthemsteger 

You are right it was added to support IE at some time, but it is not needed anymore. I have moved from the dependencies in v1.2.0.

Thanks for the feedback.

**Comment by arqex** [comment]
Sorry, v1.2.0 born broken. Use v1.2.1 instead
