### ISSUE TITLE
Calendar does not expand containing DIV and is obscured

### ISSUE THREAD

**Issue by Develliot** [arqex/react-datetime#20]
Could the css be amended so the css for .rdtPicker has a relative position instead of absolute?

**Comment by Develliot** [comment]
<img width="447" alt="screen shot 2015-09-07 at 18 15 30" src="https://cloud.githubusercontent.com/assets/5347198/9721026/7d1890e8-558c-11e5-8703-46bf82a83c97.png">

**Comment by arqex** [comment]
You could apply your own styles to the classes in order to override default ones. Couldn't you?
