### ISSUE TITLE
Add 'open' prop to show or hide picker which 'input' is true

### ISSUE THREAD

**Issue by tzwm** [arqex/react-datetime#21]
The picker will not be hide when I click the date on the picker. I need to click anywhere outside the picker to close the picker. How about adding a 'open' prop to control this?

**Comment by arqex** [comment]
Thanks for telling me.

I imagine this is an issue if the picker gets in the middle of some interaction. But I can't close it automatically, otherwise it would be impossible to select the time.

Open property would be nice that can be changed on selection, let me think of it.

**Comment by arqex** [comment]
open property added as for v1.2.1, thanks

**Comment by tzwm** [comment]
Thanks for it.
