### ISSUE TITLE
Can't reset to empty value after a date be selected.

### ISSUE THREAD

**Issue by mrbone** [arqex/react-datetime#23]
when i use react-datetime in form, 
i wana reset the input value to empty after user click the reset button.

I set the component's value props to '', 
but it's still have a date string in the input filed, 
i can only reset it to empty if i set the state 'inputValue' to empty.
is there anyway i can only control the props to reset the value ?

**Comment by arqex** [comment]
Thanks @mrbone 

I will fix that in the next release. Stay tuned :)

**Comment by arqex** [comment]
Fixed

**Comment by D0HaTeJIJI0** [comment]
I'm sorry, but it is not fixed
