### ISSUE TITLE
can not close the other Datetime compoent by using react-onclickoutside@0.3.3.

### ISSUE THREAD

**Issue by mrbone** [arqex/react-datetime#24]
The mousedown event just trigger once by using the 0.3.3 version of react-onclickoutside.

I reinstall the 0.3.1 version fix the problem.

**Comment by arqex** [comment]
It is working for me using react-onclickoutside 0.3.3. Anybody else is having this problem?

**Comment by mrbone** [comment]
@arqex I think it's the react-onclickoutside's problem.

It update by using stopImmediatePropagation which prevent all other listeners except the first one in document.
check this issue [#40](https://github.com/Pomax/react-onclickoutside/issues/40)

**Comment by arqex** [comment]
Last react-datetime version has react-onclickoutside 0.3.4 dependency that I expect to fix that problem.

**Comment by mrbone** [comment]
problem solved.
