### ISSUE TITLE
Add support for React 0.14

### ISSUE THREAD

**Issue by AlesJiranek** [arqex/react-datetime#28]
Hello, is it possible to add support for React 0.14?

**Comment by arqex** [comment]
What do you need to be updated? it is working ok for me with React 0.14

**Comment by AlesJiranek** [comment]
It is working, but ti is showing warnings about using React.DOM instead of new react-dom

**Comment by snowcxt** [comment]
Could you fix this issue?

**Comment by arqex** [comment]
Latest version should work with react 0.14 without problems. Thanks for your feedback

**Comment by code4aman** [comment]
Hi! Looks like react 0.14.x not fully supported yet, just try to upgrade your codepen.io snippet to react 0.14.x, drop-down calendar not closing on outside click event
