### ISSUE TITLE
Latest npm package is missing crucial files

### ISSUE THREAD

**Issue by anateus** [arqex/react-datetime#3]
After `npm install` (with react-datetime version 0.4.0) the `node_modules/react-datetime` directory contains the following:

```
$ ls
css  DateTime.js  gulpfile.js  LICENSE  node_modules  package.json  README.md  test
```

The `DateTime.js` file expects there to be a `src` directory, and I think you might also want there to be a `dist` dir in there.

Seems to be some sort of packaging error.

**Comment by marquex** [comment]
Yes, you are right. Strange, isn't it? I will try to publish it again. Thanks for the feedback.

**Comment by arqex** [comment]
Hi @anateus 

In version 0.4.2 it should be working ok.
