### ISSUE TITLE
Add event to onChange

### ISSUE THREAD

**Issue by fandrupaw** [arqex/react-datetime#301]
It would be nice to add `e` to `onChange`

`onChange(e, date) { ... }`

this can be helpful to eg play with keyboard events

**Comment by simeg** [comment]
Hi @fandrupaw. I agree that this would be useful, however returning the event as the first argument would be breaking the API of the component. Adding it as the second argument would be better, but then it would be inconsistent with pretty much the entire world :P But I guess having it as second argument is better than nothing. I'll look into it.

**Comment by tankorsmash** [comment]
Just to jump on here, maybe this isn't the best way of writing my forms, but I've got it so the onChange callback sets the state through `e.target.name` and it doesn't seem like it's as possible to do with react-datetime, so I've had to create a separate callback for each of the form fields with only the hardcoded name value being set to the state differing.

Anyway, all that to say I'm looking forward to hearing an update to this, good or bad!

**Comment by nkmekal1** [comment]
on the same boat. In a scenario where there are multiple date-time controls on the form, wondering if there is a way or work around to identify which date-time element was selected within the onChange event? any suggestions?

**Comment by sayuti-daniel** [comment]
@simeg Are you gonna add this to the v3 release? I'd like to see all event callback to have consistent API. 

```js
onBlur(event, props);
onChange(event, props);
onFocus(event, props);
onViewModeChange(event, props);
```

I'd be glad to help.

**Comment by jsprow** [comment]
@tankorsmash I use the same pattern to set state, especially when there are more than a couple inputs. I've also tried what I assume is a similar workaround.

In case it helps anyone (or I'm a dumb-dumb and shouldn't be doing this), here's the usual pattern I use for setting state from an input:
```javascript
handleInput = event => this.setState({ [event.target.name]: event.target.value });

...

<input
  type="text"
  onChange={this.handleInput}
  name="nameOfThing"
  value={this.state.nameOfThing}
/>
```

To get around the lack of an event being passed to the `onChange` listener(?), I added a method specifically for the `DateTimePicker` when I use more than one of them:
```javascript
handleDateTimePicker = (moment, name) => this.setState({ [name]: moment.toDate() });

...

<DatePicker
  onChange={moment => this.handleDatePicker(moment, 'nameOfThing')}
  value={this.state.nameOfThing}
/>
```

**Comment by arqex** [comment]
Hey sorry for arriving late here. react-datetime's `onChange` is not related to a single kind of event, it can happen:
* by editing the input
* by clicking on a day or changing the time in the picker

That's why the event is not returned, because it wouldn't be consistent. 

But we can still listen to those single individual events independently.

If we use `inputProps` we can listen to input's `change` events, getting the event itself.

For example, by using `renderDay` we can override also the `click` event listener when selecting a date.

If we need to listen to a specific user interaction we have our ways.
