### ISSUE TITLE
Consider namespacing all classes?

### ISSUE THREAD

**Issue by ifunk** [arqex/react-datetime#32]
I'm getting some conflicts with other classes applying styles to react-datetime component parts.

Would you consider namespacing all classes? eg.
```
td.month,
td.year {
	height: 50px;
	width: 25%;
	cursor: pointer;
}
td.month:hover,
td.year:hover {
	background: #eee;
}
```
could be changed to

```
.rdtMonth,
.rdtYear {
	height: 50px;
	width: 25%;
	cursor: pointer;
}
.rdtMonth:hover,
.rdtYear:hover {
	background: #eee;
}
```

and

```
.rdtPicker th.switch {
  width: 100px;
}
```

could be changed to:

```
.rdtSwitch {
  width: 100px;
}
```

**Comment by arqex** [comment]
All the classes are namespaced in the latest version. Thanks for the feedback.
