### ISSUE TITLE
Input value in different timezone

### ISSUE THREAD

**Issue by martinmacko47** [arqex/react-datetime#338]
```
[ ] Bug report
[X] Feature request
[ ] Support request
```

Documentation for *utc* option says: "When true, input time values will be interpreted as UTC. Otherwise they will default to the user's local timezone.". Is there a way to interpret input values as a different timezone then UTC and then the user's local timezone?

For instance the user is in London and has local timezone `Europe/London` but he is inputing date and time of an event happening in Los Angeles and therefore want's to input the value in timezone `America/Los_Angeles`. Is it possible to configure `react-datetime` component to input the value in the specified timezone?

I could just let the value be interpreted in UTC (or the user's local timezone) and then use moment.js to hack the result as if it were entered in the desired timezone. But this will be error prone. Mainly because of different DST. 

Note, that I don't want to change user's local timezone globaly, because there could be multiple fields with different input timezones on a single page.

**Comment by cogwirrel** [comment]
I needed different timezones too so I overwrote the [localMoment](https://github.com/YouCanBookMe/react-datetime/blob/master/DateTime.js#L376) method which does the parsing:

```
import Datetime from 'react-datetime';
import moment from 'moment-timezone';

class TimezoneDatetime extends Component {
    constructor(props) {
        super(props);
        this.overrideMethod = this.overrideMethod.bind(this);
    }

    overrideMethod(component) {
        // Override the 'localMoment' method to enable timezones
        if (component) {
            component.localMoment = this.localMoment;
        }
    }

    localMoment(date, format, inProps) {
        // Return a moment of the appropriate timezone
        const props = inProps || this.props;
        return moment.tz(date, format, props.timezone);
    }

    render() {
        return <Datetime {...this.props} ref={this.overrideMethod} />;
    }
}

TimezoneDatetime.propTypes = {
    timezone: PropTypes.string.isRequired,
};
```

Not the neatest solution but it worked for my use-case :)

**Comment by simeg** [comment]
@martinmacko47 This is not possible today, but would be a useful feature in the future.

**Comment by nerfologist** [comment]
Hi, I'm also in the process of trying to adapt this nice component to take an additional timezone parameter. I tried simply extending the original component this way:

(NOTE: this does not work)
```
import Datetime from 'react-datetime';
import moment from 'moment-timezone';

class TimezoneDatetime extends Datetime {
  localMoment(date, format, inProps) {
    const props = inProps || this.props;

    if (!props.timezone) {
      return super.localMoment.apply(this, arguments);
    }

    return moment.tz(date, format, props.timezone);
  }
}
```
but it was positively not triggering the overridden method. The reason being the original `Datetime` component is written using the old React `createClass` syntax. So I guess I'm also going the @cogwirrel way (thanks for your solution, by the way).

**Comment by Fabianopb** [comment]
I came recently across this too. We use this component in a product in which the customer can have access to different sites around the world and we need to have it working in the site's local time (i.e. supporting different timezones).

Exposing a `timezone` prop and setting the internal moment in that timezone is a solution. How are the plans for including this feature? This is something I could possibly work on.

**Comment by nerfologist** [comment]
Any news on this? It would be greatly beneficial to our use case.

Thanks 👍

**Comment by Fabianopb** [comment]
@nerfologist a workaround we've done is to set the default timezone before the component loads (where, it might depend on your needs).

In our case we wrap this component in a class to use along with redux-form, an within this class we simply have:
```js
componentDidMount() {
  // as you can see we pass the timezone to the class via props
  moment.tz.setDefault(this.props.timezone);
}
```

But of course, it would be much more straightforward to pass the timezone prop directly into `react-datetime`. Ping @simeg, if that's in the roadmap and nobody is working on that yet I could take a look.

Related issue: https://github.com/YouCanBookMe/react-datetime/issues/342

**Comment by Fabianopb** [comment]
@nerfologist could resetting the default timezone on `componentDidUpdate` work (and be justified) in this case?

**Comment by nerfologist** [comment]
I'll test such a workaround class in a code sandbox and see if it's viable. Thanks again @Fabianopb!

**Comment by arqex** [comment]
We can use `displayTimeZone` prop now. Thanks for being so helpful!

**Comment by sirajalam049** [comment]
This isn't working. It is crashing, saying, i.a.tz is not a function.

**Comment by redamsy** [comment]
> This isn't working. It is crashing, saying, i.a.tz is not a function.

u need to install this library https://www.npmjs.com/package/moment-timezone

**Comment by esmondleung** [comment]
> > This isn't working. It is crashing, saying, i.a.tz is not a function.
> 
> u need to install this library https://www.npmjs.com/package/moment-timezone

Do you need to do anything else after installing that library?

**Comment by GJmelody** [comment]
Installed the library but still got the same error. Thoughts?
