### ISSUE TITLE
dist version is outdated: OnClickOutside doesn’t work with multiple Datetime components

### ISSUE THREAD

**Issue by poke** [arqex/react-datetime#35]
If you have two Datetime components on a single page, then clicking outside of the the calendar for the second will not close it. You can easily reproduce this by using the [linked demo codepen](http://codepen.io/arqex/pen/BNRNBw) and changing the JavaScript code to the following:

```
React.render(
  <div>
    <Datetime />
    <Datetime />
  </div>,
  document.body
);
```

So while trying to figure out why this happened, I noticed that you just need to rebuild the dist files in order to fix this (i.e. `npm run build` is all it took me to fix this).

**Comment by arqex** [comment]
This is fixed in the latest version.
