### ISSUE TITLE
renderMonth fixed string length issue in other locale (eg: 'vi' )  

### ISSUE THREAD

**Issue by viiiprock** [arqex/react-datetime#350]
When I use `moment.locale('vi')`, I find that all `months`  render on table is `Th0` & `Th1`
It happens from the `var strLength = 3` line 88 **MonthsView.js**
Is there possible way to change it ? I need to change to `4` for my country language.
Thanks!

**Comment by simeg** [comment]
Hi @viiiprock.

The calendar is designed to be a certain width, and unfortunately it's not that easy to make it more dynamic. Maybe 4 characters would be ok, maybe you could create a PR? We could have an additional prop for the length of the week days.

**Comment by viiiprock** [comment]
Thanks @simeg 
I've forked and examine with react 16, and it works well with 4 characters. 
I have a bit of busy in several of days, will try to make a PR.

**Comment by arqex** [comment]
Hey sorry for the delay. Months are working ok in the new version 3.
