### ISSUE TITLE
Customize Time rendering?

### ISSUE THREAD

**Issue by Deseao** [arqex/react-datetime#423]
### I'm Submitting a ...

```
[ ] Bug report
[ ] Feature request
[ x] Support request
```
Is there a way to customize the way time renders? I'd like the user to be able to type in the hours, minutes, and seconds instead of relying solely on the arrows. 

### Steps to Reproduce

Click on the time field
### Expected Results

Be able to type time values into the hour, minute, second fields. Alternatively, have a renderTime prop to provide a custom rendering.
### Actual Results

Only the year, month, and day views can be customized.

**Comment by abhinavsingi** [comment]
You can fork this repo and then render time component in the main file

**Comment by arqex** [comment]
Hey sorry for the late response! In the newest version 3 you can use the `renderView` prop to customize any of the views of the picker 🙂
