### ISSUE TITLE
Feature request for onMonthChange callback

### ISSUE THREAD

**Issue by Enrichme-Admin** [arqex/react-datetime#429]
### I'm Submitting a ...

```
[ ] Bug report
[ x] Feature request
[ ] Support request
```

I have a use case where I am using network queries for determining the validity of date options supplied to the `isValidDate` callback.

Each time the month view is changed my app makes a network call to determine if an event is bookable in the newly selected month. Unfortunately Datetime doesn't provide callback options for when a month changes, so I have to apply separate javascript event handlers to the `rdtNext` and `rdtPrev` table headers to initiate the network requests. This solution isn't very elegant.

If an `onMonthChange` callback was added I could trigger a network request from that and feed the results into `isValidDate` on subsequent rendering.

Thanks

Stuart

**Comment by simeg** [comment]
This is a good idea for v3 I think. It could of course be implemented for the current version as well.

**Comment by kkurdupov** [comment]
Vote!
I suspect that callback like onYearChange also could be useful.

**Comment by arqex** [comment]
Hey sorry for the late response! Have a look at the new props in version 3 `onNavigateBack` and `onNavigateForward`.
