### ISSUE TITLE
How to block manual date/time entry?

### ISSUE THREAD

**Issue by ir-fuel** [arqex/react-datetime#46]
Hi

I would like to keep the input field + click on it to open the picker, but I would like to disable the possibility for someone to actually type in that field.

Is that possible somehow?

**Comment by timothyarmes** [comment]
This would be a nice feature. Since we're using React I'd expect it could be quite easy for this project to use a controlled input field to prevent the use typing into it....

**Comment by arqex** [comment]
I suppose you can use `inputProps` option

```
<DateTime inputProps={{disabled:true}} />
```

**Comment by ir-fuel** [comment]
If I am not mistaken that completely blocks the component. Clicking will not open the picker in that case.

**Comment by ir-fuel** [comment]
Found the solution:

`<DateTime inputProps={{readOnly:true}} />`

**Comment by timothyarmes** [comment]
That's great!

**Comment by greenais** [comment]
Probably should be added to the docs

**Comment by simeg** [comment]
@ir-fuel nice to see you found the solution!

@greenais it's actually in the documentation, but I agree that it could be highlighted a bit more:

> **`inputProps`**: Defines additional attributes for the input element of the component. For example: `placeholder`, `disabled`, `required` and `name`.

**Comment by otelom** [comment]
Even though it works it is not very pretty having the mouse becoming a "forbidden icon" and having the input grayed out.
I think that there should be a way to make this work without using a common readOnly prop.

**Comment by simeg** [comment]
@otelom On Chrome 64 and Safari 11 it doesn't do this (at least not on Codepen). It just looks like normal but you cannot input anything in the input field. What is the code you are running?

**Comment by otelom** [comment]
@simeg, I'm running Chrome 64 on W7 and Android and both show me the same thing.
`import Datetime from 'react-datetime';
<Datetime
                                timeFormat={false}
                                inputProps={{placeholder:"Clique para escolher uma data"}}
                                //defaultValue={new Date()}
                                dateFormat="DD/MM/YYYY"
                                onChange={(value) => this.setState({ data: value})}
                                closeOnSelect = {true}
                                inputProps={{readOnly:true}}
                            />`

![image](https://user-images.githubusercontent.com/12788894/36206343-ebbd3790-1189-11e8-9dfc-b7ec9ac99cd6.png)

As you can see I think I'm doing everything right but it still doesn't work as expected.

**Comment by otelom** [comment]
I got it working with [this](https://github.com/YouCanBookMe/react-datetime/issues/339#issuecomment-365659985) suggestion.

**Comment by monish96** [comment]
<Datetime
                        value={this.state.to_date}
                        closeOnSelect={true}
                        inputProps={{
                          placeholder: "Select Date",
                          disabled: this.state.isLoading,
                          readOnly: false,
                          onKeyDown: (e) => e.preventDefault(),
                        }}
                        dateFormat={"YYYY-MM-DD"}
                        timeFormat={false}
                        onChange={(date) => this.handleDate(date)}
                      />
This will work. I hope this helps some one
