### ISSUE TITLE
Setting the default time Toggle without setting a default Datetime

### ISSUE THREAD

**Issue by danvc** [arqex/react-datetime#462]
Is there a way to set/change the default time that is displayed in the time selector (that is set 12:00 AM by default) without specifying a value to the component?

For example: By default the current date is shown in the Date dialog, however, the time is always 12:00 AM by default.

Is there a way to change this time, without setting a default value to the component (like ```moment().format("MM/DD/YYYY 09:00 a")```)?
![image](https://user-images.githubusercontent.com/24215587/32644082-8e5c6cba-c5c6-11e7-97cc-ff6d7547c07a.png)

**Comment by deanhamilton11** [comment]
Would it be acceptable to have props like this:
defaultHour={14}
defaultMinute={30}

Or should this be accomplished some other way?

**Comment by omkar-joshi** [comment]
+1

**Comment by arqex** [comment]
Hey! Sorry for the delay in the reply. In version 3 you have the `initialViewDate` prop, that can be used to define the date and time shown when the user opens the picker for the first time.
