### ISSUE TITLE
Allow renderTime

### ISSUE THREAD

**Issue by MarciDavid** [arqex/react-datetime#479]
Hi

It'll be nice to allow a renderTime which can get a custom component.
Attached an image for demonstration.

![capture](https://user-images.githubusercontent.com/22189520/33543259-0c2d0066-d8df-11e7-92e7-d616947e7e50.PNG)

**Comment by bsantos09** [comment]
@MarciDavid How did you manage to display the custom time component? Thanks

**Comment by arqex** [comment]
In version 3 the prop `renderView` is available and it allows to override any view in react-datetime.
