### ISSUE TITLE
renderInput missed in TypeScript definitions

### ISSUE THREAD

**Issue by Zaitsev** [arqex/react-datetime#482]
no method renderInput in interface DatetimepickerProps

**Comment by SuperOleg39** [comment]
Same problem!

Can i make a pr, `renderInput: (props: any, openCalendar: () => void) => JSX.Element;` ?

**Comment by entrikontra** [comment]
Same problem!

any solution for this one?

**Comment by simeg** [comment]
PRs are always welcomed! We review them when we have time.

**Comment by dominikeinkemmer** [comment]
@simeg I tried to create a PR that adds the typings but I can't push my branch, I get an unauthorized error :( anything I need to do before I can push anything?

**Comment by simeg** [comment]
@dominikeinkemmer You need to fork this repo, create a branch, push to that branch and then make a PR from that branch -> this repo. You get unauthorized error because you are trying to push to this branch, which you are not authorized to do. I hope this makes sense.

**Comment by dominikeinkemmer** [comment]
@simeg ah I see, thank you :)

**Comment by coderunner007** [comment]
@simeg @dominikeinkemmer  Is this fixed yet?

**Comment by ElysiumTan** [comment]
I needed this for my project, so I have submitted a pull request with exactly that.

**Comment by gbersac** [comment]
I can't find type definition for this package. How do you install types for this ?

**Comment by Zaitsev** [comment]
You don't need to install.  https://github.com/YouCanBookMe/react-datetime/blob/master/DateTime.d.ts

**Comment by arqex** [comment]
This is fixed in version 3. Sorry for the delay in fixing it!
