### ISSUE TITLE
onBlur feature request

### ISSUE THREAD

**Issue by baweinbe** [arqex/react-datetime#492]
Not really an issue because it works how it says in the docs, but why does the onBlur event only get fired if the date is valid? Personally, I would like it if the event were fired regardless of date validity (e.g. "last week" is an acceptable input for my application)

**Comment by simeg** [comment]
Good point. I'm not sure why it's implemented that way. It makes sense that `onBlur` should be deterministic. Will label as bug.

**Comment by lukezavrel** [comment]
Is there any progress in this issue? Would be nice to get this fixed

**Comment by crobinson42** [comment]
I am running into onblur issues as well - onBlur will **only** fired when calendar is open or there is focus in the input field and user hits "tab" key.

**Comment by daani786** [comment]
`onBlur ` is also not working for me, once it works only when i press `tab` or `select` a date from opened calendar.

**Comment by lukezavrel** [comment]
I found a workaround that suits my needs, so maybe it could help somebody. The issue with it is the fact that "onBlur" action will be called every time user clicks outside the datetime component (even if it wasn't focused before). In my case I only need to know if the datetime input has focus, so the unintended calls get ignored.

```javascript
componentDidMount() {
  if (this.input) {
    let origClickOutside = this.input.handleClickOutside;
    this.input.handleClickOutside = () => {
      origClickOutside();
     //your intended behaviour here
      this.onBlur();
    };
  }
}

onBlur() {
  //onBlur behaviour
  if (this.state.focused) {
    this.setState({ focused: false });
  }
}

render() {
  return (
    <DateTime value={this.state.value}
      closeOnSelect={true}
      onChange={this.onChange.bind(this)}
      onBlur={this.onBlur}
      ref={(ref) => this.input = ref}
      inputProps={{ onFocus: this.onFocus }} />
  );
}
```

**Comment by arqex** [comment]
In the new version 3 `onBlur` has been renamed to `onClose`. It's a better name, since it's triggered when the calendar picker is closed.

If anybody is interested in the real `onBlur` method of the `input`, it's possible to use the prop `inputProps` to pass the listener direct to the input:

```jsx
<Datetime inputProps{{onBlur: e => console.log('Blur!!!', e)}} />
```
