### ISSUE TITLE
Maximum viewModeLevel

### ISSUE THREAD

**Issue by ZeroCool-85** [arqex/react-datetime#493]
### I'm Submitting a ...

```
[ ] Bug report
[x] Feature request
[ ] Support request
```

My problem is, I don´t want and need the 'years' viewMode from the datePicker. Is it possible to add a prop for handling the maximum viewModeLevel to get only for example time, days and months.

**Comment by arqex** [comment]
Duplicated https://github.com/arqex/react-datetime/issues/726
