### ISSUE TITLE
renderInput button fires openCalendar but only opens on second click.

### ISSUE THREAD

**Issue by rluiten** [arqex/react-datetime#501]
### I'm Submitting a bug.

```
[x ] Bug report
[ ] Feature request
[ ] Support request
```
I am using 
* react@15.6.1
* react-datetime@2.12.0

Tested in Windows 10 on browsers

* Chrome 64 
* Firefox 58
* IE 11,
* Edge 41

### Steps to Reproduce
Created a Datetime field, passed in custom `renderInput` it renders a bootstrap input-group
with a Input field readonly and a clickable calendar icon on end.

![image](https://user-images.githubusercontent.com/670472/35714943-6094123c-081b-11e8-8046-af80844de5da.png)

My current renderinput
```typescript
  renderInput = (props: any, openCalendar: () => void) => (
    <div className="input-group datepicker-control">
      <input {...props} readOnly maxLength={100} />
      <div className="input-group-addon" onClick={openCalendar}>
        <i className="fa fa-calendar fa-lg" />
      </div>
    </div>
  );
```
The props passed into renderInput are as follows from react-datetime.
![image](https://user-images.githubusercontent.com/670472/35715144-7909ceb4-081c-11e8-9568-0b5c8c3dce40.png)

### Expected Results
If I click on the calendar icon the calendar opens.

### Actual Results
Only on second click does the calendar icon open, not the first one.

### Minimal Reproduction of the Problem
This codepen __does not show the problem__ I included it just in case its useful anyway to someone.
https://codepen.io/anon/pen/jZboPN?editors=0010
I am using redux and redux-forms and am not ready to try and add that to example to see if it might change behaviour at moment.

NOTE: I had to build a local 2.12.0 and copy it into the upper part of the codepen javascript to get a 2.12.0 version in the browser. Search for "// EXAMPLE STARTS HERE" to get to actual demo.

### Other Information (e.g. stacktraces, related issues, suggestions how to fix)

I believe I have a fix, but when I pulled the repo locally I could not figure out how to create a failing test, your basic renderInput test case appears to work.

in `Datatime.componentWillReceiveProps`
```javascript
if ( updatedState.open === undefined ) {
	if ( typeof nextProps.open !== 'undefined' ) {
		updatedState.open = nextProps.open;
	} else if ( this.props.closeOnSelect && this.state.currentView !== 'time' ) {
		updatedState.open = false;
	} else {
		updatedState.open = this.state.open;
	}
}
```

Change this line from
```javascript
} else if ( this.props.closeOnSelect && this.state.currentView !== 'time' ) {
```
to
```javascript
} else if ( this.props.closeOnSelect && this.state.currentView !== 'time' && typeof nextProps.open !== 'undefined' ) {
```
appears to fix the problem for me at the moment.

I have also come up with a work around that solves the behaviour for me without changing v2.12.0.
Do one of the following in my renderInput click handler for the calendar icon.
* click() and then 50 msec later click()
* focus() and then 50 msec later click() 
This makes a click on the calendar icon open calendar consistently in the browsers mentioned above.

Running focus() and then 50 msec later focus()  does not change the 2 click required behaviour.
I am using focus() then click() as it nicely focus the input for a consistent look.

This code works for me first click on calendar opens calendar consistently.
```typescript
  private textInput: HTMLInputElement;

  getTextInputRef = (ref: HTMLInputElement) => {
    this.textInput = ref;
  };

  activateInput = () => {
    if (this.textInput) {
      this.textInput.focus();
      setTimeout(() => this.textInput.click(), 50);
    }
  };

  renderInput = (props: any) => {
    return (
      <div className="input-group datepicker-control">
        <input {...props} readOnly maxLength={100} ref={this.getTextInputRef} />
        <div className="input-group-addon" onClick={this.activateInput}>
          <i className="fa fa-calendar fa-lg" />
        </div>
      </div>
    );
  };
```

**Comment by simeg** [comment]
Thanks for the thorough bug explanation. Will look into this.

**Comment by MathieuVedana** [comment]
Hello team,

Facing same annoying issue here also. Nobody fix this since lamost one year, can't beleive it :P

**Comment by arqex** [comment]
Hey! Sorry for the delay on the reply, this is fixed in version 3.

**Comment by haeunFassto** [comment]
Hmm. it still happens to me and i use ver 3.0.4
