### ISSUE TITLE
onBlur doesn't trigger when using open prop

### ISSUE THREAD

**Issue by SachaG** [arqex/react-datetime#509]
### I'm Submitting a ...

```
[x ] Bug report
[ ] Feature request
[ ] Support request
```

I'm using

- react@16.2.0
- react-datetime@2.12.0

When I open a calendar the normal way, as you can see I'm also able to close it by clicking anywhere outside of the field: 

![https://d3vv6lp55qjaqc.cloudfront.net/items/0k3v1O1z2P2I1t0O1M2D/Screen%20Recording%202018-02-08%20at%2011.23%20AM.gif?X-CloudApp-Visitor-Id=f25ee64a8f9b32be400086060540ffac&v=d4cb8457](https://d3vv6lp55qjaqc.cloudfront.net/items/0k3v1O1z2P2I1t0O1M2D/Screen%20Recording%202018-02-08%20at%2011.23%20AM.gif?X-CloudApp-Visitor-Id=f25ee64a8f9b32be400086060540ffac&v=d4cb8457)

Yet when that calendar has been opened by passing `open = {true}` as a prop, the `onBlur` event doesn't trigger anymore and the calendar cannot be closed by clicking outside: 

![https://d3vv6lp55qjaqc.cloudfront.net/items/043b1i163i2A3z162Q0C/Screen%20Recording%202018-02-08%20at%2011.23%20AM.gif?X-CloudApp-Visitor-Id=f25ee64a8f9b32be400086060540ffac&v=0cb269f6](https://d3vv6lp55qjaqc.cloudfront.net/items/043b1i163i2A3z162Q0C/Screen%20Recording%202018-02-08%20at%2011.23%20AM.gif?X-CloudApp-Visitor-Id=f25ee64a8f9b32be400086060540ffac&v=0cb269f6)

**Comment by simeg** [comment]
Hi @SachaG. Thanks for the detailed bug information, it makes it so much easier for us to understand. This indeed seems like a bug.

**Comment by simeg** [comment]
Have you tried using `closeOnSelect`? It's `false` by default. I'm investigating the `onBlur` issue.

**Comment by simeg** [comment]
This seems to be the problem: https://github.com/YouCanBookMe/react-datetime/blob/master/DateTime.js#L350

**Comment by rizzomichaelg** [comment]
What about something like this?
```
handleClickOutside: function() {
		if ( this.props.input && this.state.open && !this.props.disableOnClickOutside ) {
			if (!this.props.open) {
				this.setState({ open: false }, function() {
					this.props.onBlur( this.state.selectedDate || this.state.inputValue );
				});
			} else {
				this.props.onBlur( this.state.selectedDate || this.state.inputValue );
			}
		}
	},
```
This might be breaking the concept of what "blurring" really means if the open prop is set, though.

**Comment by giulioambrogi** [comment]
Any update on this?

**Comment by johnhunter** [comment]
I'm seeing the same issue. It seems that when `open=true` neither onFocus or onBlur fire.

See demo at: https://codepen.io/johnhunter/pen/LgmOXQ?editors=0111

**Comment by gaston-niglia** [comment]
Hi guys, is there any update on this? any workaround? Thanks

**Comment by johnhunter** [comment]
@gaston-niglia I have a fork with a fix at https://github.com/Apperio/react-datetime

**Comment by mankutila** [comment]
Faced this issue. Is there any workaround?

**Comment by johnhunter** [comment]
@mankutila The PR https://github.com/YouCanBookMe/react-datetime/pull/573 solves the issue but is open with merge conflicts.

**Comment by arqex** [comment]
In the new version 3 `onBlur` has been renamed to `onClose`. It's a better name, since it's triggered when the calendar picker is closed.

If anybody is interested in the real `onBlur` method of the `input`, it's possible to use the prop `inputProps` to pass the listener direct to the input:

```jsx
<Datetime inputProps{{onBlur: e => console.log('Blur!!!', e)}} />
```
