### ISSUE TITLE
Triangle for today's date is sometimes positioned incorrectly

### ISSUE THREAD

**Issue by kaiyoma** [arqex/react-datetime#521]
### I'm Submitting a ...

```
[ ] Bug report
[ ] Feature request
[x] Support request
```

### Steps to Reproduce
Put a datetime picker (without an input) into a Blueprint popover.

### Expected Results
Everything should work as normal.

### Actual Results
The triangle for today's date is positioned incorrectly in IE and Edge. Those browsers won't let me inspect the `::before` element, so I can't see if any of the styles are wrong. Any idea on how this could get positioned incorrectly?

### Other Information (e.g. stacktraces, related issues, suggestions how to fix)
![misplaced-triangle](https://user-images.githubusercontent.com/10719780/36287385-58cf6670-1269-11e8-93b8-94832bcbded3.png)

**Comment by kaiyoma** [comment]
I'm seeing the same exact problem when using a react-bootstrap overlay (as opposed to a Blueprint popover). Maybe this happens when react-datetime has an ancestor who has `position: absolute` or `position: fixed`?

**Comment by arqex** [comment]
There must be some styles conflict with the css in your page. BTW that range picker looks great!
