### ISSUE TITLE
Minutes picker

### ISSUE THREAD

**Issue by AlexFedorovSWE** [arqex/react-datetime#530]
### I'm Submitting a ...

```
[ ] Bug report
[x] Feature request
[ ] Support request
```
Inside the timepicker you can click on minutes and choose from the list of predefined values from 0 to 60 with step 5.
![p1](https://user-images.githubusercontent.com/736073/36969378-5de975f4-2076-11e8-8f2d-1bb64ffa8a61.png)
![p2](https://user-images.githubusercontent.com/736073/36969380-5e9fde20-2076-11e8-9d8c-fb529290bee9.png)

**Comment by arqex** [comment]
Hey sorry for the late response! In the newest version 3 you can use the `renderView` prop to customize any of the views of the picker 🙂
