### ISSUE TITLE
open={false} does not close calendar

### ISSUE THREAD

**Issue by mattcopas** [arqex/react-datetime#546]
### I'm Submitting a ...

```
[X ] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce

1. Add a Datetime component to your component...
<Datetime open={false} />
### Expected Results

The date picker should not be open
### Actual Results

The date picker is open
### Other Information (e.g. stacktraces, related issues, suggestions how to fix)
 
I know this was (apparently) fixed by https://github.com/YouCanBookMe/react-datetime/pull/476/files (I am using 2.14.0) but it's still broken for me...

**Comment by vmurillo** [comment]
Same for me

**Comment by hmcooper** [comment]
I am having the same issue as well. working on a new React-Redux application, I installed both react-datetime and moment to my application, dropped a <Datetime /> component one of my components, and the calendar was displayed, and no amount of effort would make it hide.

**Comment by retrodeluxe** [comment]
Same here, the component seems to be not usable.

**Comment by geoguide** [comment]
I'm confused. So it is open when you load the page with that setting? Or it opens when you put focus in the field?

**Comment by geoguide** [comment]
Hm I'm not seeing this behavior. Would it be easy to share it behaving this way?

**Comment by ConnectedReasoning** [comment]
Thanks izgeorge, this worked for me. The instruction to add the stylesheet should be located in the installation instructions

**Comment by arqex** [comment]
Hey sorry for the late response! This is not happening anymore in v3. 🙂
