### ISSUE TITLE
Setting number of cells, (days), for each row 

### ISSUE THREAD

**Issue by reft** [arqex/react-datetime#547]
### I'm Submitting a ...
```
[ ] Bug report
[X ] Feature request
[ ] Support request
```

### Expected Results
Currently each row has 7 cells, (days). Would it be possible to add a configuration for this so you can set a different value? 

I'm using react-datetime in full width and I would like put all the days in one single row if possible.
I've tried the custom renderDay method but I can not change the number of cells for each row..

**Comment by arqex** [comment]
Hey sorry for the late response! In the newest version 3 you can use the `renderView` prop to customize any of the views of the picker 🙂
