### ISSUE TITLE
Render a button to select the date

### ISSUE THREAD

**Issue by rafaelcardososilva** [arqex/react-datetime#548]
### I'm Submitting a ...

```
[ ] Bug report
[ ] Feature request
[x] Support request
```

### Expected Results

I need to select the date by button.
Is there a way to insert the button into the component?

### Minimal Reproduction of the Problem

![image](https://user-images.githubusercontent.com/5940728/39604019-ddbffeb6-4f00-11e8-82d8-413f324cc09b.png)

**Comment by arqex** [comment]
Hey sorry for the late response! In the newest version 3 you can use the `renderView` prop to customize any of the views of the picker 🙂. See the second example at https://github.com/arqex/react-datetime#customize-the-datepicker-appearance
