### ISSUE TITLE
Changing time should not auto select first of the month when isValidDate is passed 

### ISSUE THREAD

**Issue by Poukai** [arqex/react-datetime#563]
### I'm Submitting a ...

```
[x ] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce

`const yesterday = Datetime.moment().subtract(1, 'day');`

`valid = (current) => {
        return current.isAfter(yesterday);
  };`

`<Datetime
      onChange={this.onChangeDate}
      {...props}
     viewDate={new Date('01-01-2018')}
      isValidDate={this.valid}
    />`
### Expected Results

If you change the time to any value the date is selected as first of 1st Jan 2018.
### Actual Results

Should not select any date.

**Comment by arqex** [comment]
Hey @Poukai 

Thanks for the feedback. I could reproduce it I'll try to ship a fix soon.

**Comment by arqex** [comment]
Sorry for the delay. This should be fixed in v3.0.4.
