### ISSUE TITLE
Create props to open time picker after selected date.

### ISSUE THREAD

**Issue by izanf** [arqex/react-datetime#566]
### I'm Submitting a ...

```
[ ] Bug report
[X] Feature request
[ ] Support request
```

### Steps to Reproduce

When user select the date, open time modal.

### Actual Results

When user select the date, the modal is closing.

**Comment by alesanchezr** [comment]
This will be awesome, sometimes the user does not know that the time can also be set.

**Comment by arqex** [comment]
In version 3 we can use
```jsx
<Datetime initialViewMode="days" updateOnView="time" />
```
https://codesandbox.io/s/long-bird-3purx?file=/src/App.js
