### ISSUE TITLE
newest version - missing renderInput

### ISSUE THREAD

**Issue by TomChimere** [arqex/react-datetime#604]
Hello,
I installed react-datetime by npm install --save react-datetime, i have the newest version (2.16.2), BUT renderInput prop isnt working, actually when i check source code of the DateTime interface, there is no renderInput, whats wrong?

**Comment by crobinson42** [comment]
@TomChimere can you provide a codepen or plunker example of your issue?

**Comment by TomChimere** [comment]
@crobinson42 Hello, dont know why is codepen needed for this, in DateTime.d.ts is no renderInput prop, i checked release versions from 2.16.2 down to 2.11.0 and its missing in all of them.

renderInput prop was introduced in 2.11.0 version - _Add renderInput prop which let's the consumer of the component render their own HTML input element_

Just click on "Code" tab here and open DateTime.d.ts, there is no renderInput prop and it should be according to release notes and actual documentation

**Comment by respectTheCode** [comment]
I just ran into the same issue

**Comment by flisboac** [comment]
Same problem here. For those using TypeScript, there's a way to (sort of) bypass this type checking by spreading an object onto the `DateTime` component, e.g.:

```jsx
function renderInput(...) {
  /* ... */
}

const JustAnExample = () => {
  const undefinedProperties = {
    renderInput
  }

  return <DateTime
    {/* other props here */}
    { ... undefinedProperties }
  />;
}
```

Not ideal, I know. But at least [`renderInput` is surely implemented](https://github.com/YouCanBookMe/react-datetime/blob/b7ea548695e61283b0b991b0094dcc2c4ac11d53/DateTime.js#L485), AFAICT.

**Comment by arqex** [comment]
We have that method out of the typescript definitions non intentionally, but it should work even if you IDE says that it's not there. This is something that will be fixed in the new v3 we are preparing.

**Comment by EddyIvan** [comment]
We can't build our project if we have typescript errors. It will be really good if you can add this function until the release of v3, because right now the v2 doesn't work with typescript, if you need the renderInput function.

**Comment by malcolmrebughini** [comment]
You can also "redefine" the component to include any missing props.

```const TypedDateTime = DateTime as React.ComponentType<
  DateTime.DatetimepickerProps & {
    renderInput?: (props: any, openCalendar: () => void, closeCalendar: () => void) => void;
    closeOnTab?: boolean;
  }
>;```

**Comment by arqex** [comment]
Hey sorry for the late response! This is not happening anymore in v3. 🙂
