### ISSUE TITLE
Version 3

### ISSUE THREAD

**Issue by arqex** [arqex/react-datetime#607]
Hey guys I started working in a version 3 of the library. The main focus of this version is get rid of reconstructing the component state from the props in the `componentWillReceiveProps` method, that it's the main reason of every problem that arises in with the component. The code is in the branch v3:

https://github.com/YouCanBookMe/react-datetime/tree/v3

It's already working ok, but it has breaking changes that break the tests and I've been tracking in the changelog. This version 3 is already faster and smaller than the current v2.16.3!

It would be great to make it stop using react's createClass and start using ES6 syntax in order to make the source code more readable. It would require to add some webpack/babel configuration and the build scripts, but unfortunatelly I don't have the time to adding it. If somebody wants to give it a try I'd be glad to add the change.

If you give it a try by `npm install react-datetime@3.0.0-alpha.2` don't hesitate to contact and share your thoughs :)

**Comment by skchen28** [comment]
Does version 3 support IE8?

**Comment by arqex** [comment]
@skchen28, mmm difficult to say. If the current version support IE8, v3 should support it too. But I don't know if the first is true.

**Comment by malcolmrebughini** [comment]
Any plans on supporting alternatives to momentjs like dayjs?

**Comment by gfortaine** [comment]
@arqex The css is missing in the package, I have opened a pull request : https://github.com/YouCanBookMe/react-datetime/pull/683

**Comment by arqex** [comment]
Finally, 4 years later, version 3 is out!! Thanks to everybody who helped in making it possible! 🎉
