### ISSUE TITLE
onChange event cannot change time 

### ISSUE THREAD

**Issue by tmclouisluk** [arqex/react-datetime#609]
My code here
`<Datetime
                        value={this.props.from}
                        onChange={this.props.onSetFrom}
                        onBlur={this.props.onClose}
                    ></Datetime>`

I dont know why it always return a moment object with 12:00am even I have set the time.
However, the date works

Does anyone know how to change the time?

**Comment by arqex** [comment]
Hey @tmclouisluk 

if `this.props.onSetFrom` actually changes `this.props.from` it should update the datepicker time. If `this.props.from` never changes, the picker will never change either even if you click on the buttons.
