### ISSUE TITLE
Value overriding viewDate option

### ISSUE THREAD

**Issue by sreekanth586** [arqex/react-datetime#618]
### I'm Submitting a ...

```
[ ] Bug report 
[x] Feature request
[ ] Support request
```

While using the reactDateTime package in my project i have a requirement where i can give the default selected date to 7 days calendar and show current month calendar view in UI using (viewDate option) when it loads calendar. When the due date occurs on next month it's overriding the viewDate option in package and showing next moth calendar in the view.
<Datetime input={false} dateFormat="DD/MM/YY" timeFormat={false} isValidDate={this.valid} renderDay={this.renderDay} viewDate={moment()} value={moment().add(7, 'days')} />

### Steps to Reproduce
 in package give value as "moment().add(7, 'days')" and viewDate as "moment()". In every month end the selected date falls into next month and calendar view changed to next month.

### Expected Results
Expected result should be, "value" in reactDateTime package should not override "viewDate" option. Calendar should load initially based on the viewDate value 

### Actual Results
Even though if i give "value" and "viewDate" in package "value" is overriding "viewDate" and calendar is showing month based on "value"

### Minimal Reproduction of the Problem

N/A

### Other Information (e.g. stacktraces, related issues, suggestions how to fix)
 
N/A

**Comment by keithpickering** [comment]
@sreekanth586 Did you ever find a solution for this? `viewDate` doesn't appear to do anything at all, with or without a `value`.

**Comment by arqex** [comment]
In version 3 the `viewDate` prop doesn't exist anymore.

You can still use `initialViewDate` and `initialViewMode` to prepare the calendar for when it's open the first time, and also `onBeforeNavigate` to intercept the navigation among views.
