### ISSUE TITLE
The use of findDOMNode is deprecated in React Strict Mode, can this be rewritten to use refs instead?

### ISSUE THREAD

**Issue by NamespaceValentine** [arqex/react-datetime#626]
### I'm Submitting a ...
```
[x] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce
Use react-datetime in react 16 with strict mode.

### Expected Results
No issues exist around findDOMNode

### Actual Results
Due to updates in react around strict mode, findDOMNode should be replaced with direct refs:
https://reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage

### Other Information (e.g. stacktraces, related issues, suggestions how to fix)
Strict Mode is required for upcoming React features such as Concurrent Mode, thus this will not work properly unless it is refactored.

**Comment by arqex** [comment]
@NamespaceValentine Thanks for your feedback.

I have opened an issue inside react-onclickoutside, that is the library we use for the autoclosing feature and the one using `findDOMNode`.

https://github.com/Pomax/react-onclickoutside/issues/315

**Comment by NamespaceValentine** [comment]
Thank you ^_^

**Comment by kkalve** [comment]
react-onclickoutside v6.9.0 has been published long time ago (should include fix), any chance of updating?

**Comment by kkalve** [comment]
@arqex seems like you updated react-onclickoutside to 6.9.0 but v3 is not using refs and `setClickOutsideRef` to prevent this Strict Mode warning.

Warning example - https://codesandbox.io/s/brave-bohr-6mcw4
react-onclickoutside usage without warning: https://codesandbox.io/s/confident-edison-0tqm8?file=/src/App.js

Any plans on updating onclickoutside usage in v3?

**Comment by arqex** [comment]
Thanks for raising the issue, and sorry for the delay! It's fixed as part of version 3 🙂

**Comment by kkalve** [comment]
@arqex My testing was on version 3.0.2 (warning still exits) and i created pull request for v3 to fix this #725  - are you planning to merge this or did i misunderstood something?

**Comment by arqex** [comment]
Hey @kkalve 

Sorry for closing the issue without checking it properly. With the release of v3 I wanted to clean up old tickets quickly to have more visibility on what's needed to be done. I was sure I was going to re-open some of them, like this one :)

I'll review the PR and try to merge today.

**Comment by arqex** [comment]
Pull request merged. Thanks @kkalve for it!
