### ISSUE TITLE
Using UMD, there is no minified css on /dist

### ISSUE THREAD

**Issue by lovato** [arqex/react-datetime#629]
After installation, I had to link CSS file from a file in a folder **/css**, brother of the folder **/dist**.
I am not sure this is a bug... Just a heads up because most of others packages I am working with have a js/css (+minified) inside /dist for UMD/CDN approach.

If this is intentional, sorry. Just close this ticket.

Best,
Marco

**Comment by arqex** [comment]
Yes, this is intentional. The styles given are optional in case the developer want to create their own ones without the need of loading default ones.
