### ISSUE TITLE
Disabling automatic UTC offset adding

### ISSUE THREAD

**Issue by belaarany** [arqex/react-datetime#631]
### I'm Submitting a ...
```
[ ] Bug report
[ ] Feature request
[x] Support request
```

### Minimal Reproduction of the Problem
I am working on an app where the timezone should be always UTC+0 instead of my PC's timezone. The problem is that I am storing data (only the time is the relevant data, so the timezone should not change it) in ISOString Zulu format (like if I want to store 8AM, I would store `2019-4-10T08:00:00Z`). However if I use this stored value as the default value for the Datepicker, it will show 10AM because I am in UTC+2 and it adds the UTC offset automatically.

Is it possible to disable this feature?

**Comment by arqex** [comment]
Please have a look at the `utc` prop.
