### ISSUE TITLE
How to render three 3 months per table row?

### ISSUE THREAD

**Issue by kboul** [arqex/react-datetime#637]
Hello,

Thank you for the library. I have a question. I would like to render 3 months or `tds` per row as I am customizing the calendar style. How can I achieve that? 

I am thinking of the `renderMonth` function which I have already used to convert months to Dutch language but any comment would be really helpful. 

Here is what I have so far:
![Screenshot from 2019-06-20 17-49-53](https://user-images.githubusercontent.com/14216599/59858545-dbd9e580-9383-11e9-89cc-3f65acc8f634.png)

Thanks in advance.

**Comment by arqex** [comment]
Thanks for raising the issue, and sorry for the delay! As part of the new version 3 you can create your own markup for any view by using the `renderView` prop-
