### ISSUE TITLE
Not able clear invalid value in case of editable mode

### ISSUE THREAD

**Issue by hgbalar** [arqex/react-datetime#640]
### 3
I am using react-datetime as a date picker. Now the issue is that if the user entered an invalid date like '12' or 'abc' and onBlur event I have called below function and it setting blank value in state however date component is not clearing the entered input '12' or 'abc'

```
onDateChange(event) {

        var value = '';

        if(event.date) { // it will be true in case of valid date only other wise value remain ''
            value = event.valueOf();
        }

        this.setState({startDate: value});
 }

```

### Steps to Reproduce

Use this this code 
```
<Datetime name="startDate"
    className="datePicker"
    value={this.state.startDate}
    timeFormat={false}
    dateFormat="DD-MM-YYYY"
    inputProps={{placeholder: "DD-MM-YYYY"}}
    onChange={e => this.onDateChange(e)}
    onBlur={e => this.onDateChange(e)}
    utc={true}/>
```
Enter wrong value like 12 in date input

### Expected Results
On blur event entered input must be clear

### Actual Results
Entered input is not getting clear on blur event

**Comment by HirenPatel2791** [comment]
you can validate the date on change with [isMoment()](https://momentjs.com/docs/#/query/is-a-moment/). 
`handleDateChange = (startDate) => {
     if(startDate && moment.isMoment(startDate))
           this.setState({ startDate });
}`
