### ISSUE TITLE
`viewDate` prop doesn't do anything 

### ISSUE THREAD

**Issue by keithpickering** [arqex/react-datetime#644]
### I'm Submitting a ...

```
[x] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce

1. Specify a moment object (or string) as a `viewDate` in the Datetime component
2. Open the date picker

### Expected Results
The date picker should open to the month of the moment object I pass as the `viewDate`, without actually selecting a date/time, as specified in the docs.

### Actual Results
The picker opens to the current month and year (July 2019) instead of the month specified in the `viewDate`.

### Minimal Reproduction of the Problem

https://codepen.io/keithpickering/pen/xvExRj

**Comment by johnfcs778** [comment]
I ran into this issue as well, it seems that upgrading react-datetime to 2.16.3 solved the problem.

**Comment by keithpickering** [comment]
@johnfcs778 is that an official release? The last tagged one in this repo is 2.16.2

**Comment by johnfcs778** [comment]
@keithpickering It's the latest version on npm: https://www.npmjs.com/package/react-datetime

**Comment by keithpickering** [comment]
@johnfcs778 That worked, thanks a ton! However just for posterity, I think there's still a bug here. A plain date string still doesn't work; I have to parse it through Moment for it to be used, like so:
`<Datetime viewDate={Datetime.moment(this.props.startDate)} />`

**Comment by arqex** [comment]
In version 3 the `viewDate` prop doesn't exist anymore.

You can still use `initialViewDate` and `initialViewMode` to prepare the calendar for when it's open the first time, and also `onBeforeNavigate` to intercept the navigation among views.
