### ISSUE TITLE
Set new default value but component doesn't rerender

### ISSUE THREAD

**Issue by Akaren13** [arqex/react-datetime#645]
I have datepicker like this

` <Datetime  closeOnTab  closeOnSelect  defaultValue={new Date(this.state.timestamp_lte)} className="timestamp_lteInput" />`

When I change the state, it doesn't rerender it in GUI. Inside of component , I can see new value but GUI is same.

**Comment by wouter140** [comment]
`defaultValue` is only used when first rendering the Datetime object and is used for **uncontrolled input**. Meaning after first render you have no control over how it represents the selected date. The component will keep the state internally when changes occur. 
It sounds like you want controlled input, in which case you should use the `value` property and the `onChange` callback.
