### ISSUE TITLE
Error with month show

### ISSUE THREAD

**Issue by ltt2801** [arqex/react-datetime#646]
### I'm Submitting a ...

```
[x ] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce

1. Open date picker
2. Click month-year to view month

### Expected Results

Th01 Th02 Th03 ... Th10 Th11 Th12
### Actual Results

Th0 Th0 Th0 ... Th1 Th1 Th1

### Minimal Reproduction of the Problem

https://codepen.io/ltt2801/pen/aeRqYq

### Other Information (e.g. stacktraces, related issues, suggestions how to fix)
 
I use moment locale tzm-latn.js and get more error with rendering table date/time picker https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/locale/tzm-latn.js

Maybe you code split 3 words for months only.

**Comment by arqex** [comment]
Thanks for raising the issue, and sorry for the delay! It's fixed as part of version 3 🙂
