### ISSUE TITLE
Pick a date with no year?

### ISSUE THREAD

**Issue by SimonChris** [arqex/react-datetime#651]
I need the user to pick a start and end date not connected to any specific year.

Is there any way to accomplish this?

**Comment by MatthewShawkat** [comment]
Hi @SimonChris,

Did you ever figure this one out?

**Comment by SimonChris** [comment]
I am afraid not. It's also a bit problematic since the length of February differs between years.

I just use the current year and remove it if I don't need it.

**Comment by MatthewShawkat** [comment]
I ended up using airbnb react dates. It doesn't have a year selector, and you can easily remove the year

**Comment by SimonChris** [comment]
Thanks :). I'll check it out.

**Comment by arqex** [comment]
duplicated https://github.com/arqex/react-datetime/issues/726
