### ISSUE TITLE
How to change locale but keep language

### ISSUE THREAD

**Issue by pdhung197** [arqex/react-datetime#653]
I'm using `react-datetime` https://www.npmjs.com/package/react-datetime to make a datetime picker for my app.  
It's look like https://codepen.io/simeg/pen/yVVjdJ.
```
var date = new Date();
React.render(
  <div>
    <Datetime input={false} locale="fr-en" />
  </div>,
  document.body
);
```  
And result is:  
![image](https://user-images.githubusercontent.com/14067307/64398581-8c0be000-d08f-11e9-98b5-990f196949fd.png)

Now I wanna change my Datetime locale to another locale (ex: Fr, de or vi) but keep Eng is language of my datetime board.  
How can? Thanks.

**Comment by arqex** [comment]
I'm sorry but all the texts in the datepicker are localized too, so if you change the locale, all the month and day names will be changed to the way they are called by the locale.
