### ISSUE TITLE
Unable to edit only minutes without hours

### ISSUE THREAD

**Issue by K1llMan** [arqex/react-datetime#658]
This part of TimeView.js
```
		if ( format.toLowerCase().indexOf('h') !== -1 ) {
			counters.push('hours');
			if ( format.indexOf('m') !== -1 ) {
				counters.push('minutes');
				if ( format.indexOf('s') !== -1 ) {
					counters.push('seconds');
				}
			}
		}
```
prevents creating counters for minutes and second if there are no hours in format string.
Is it feature? Can it be changed to edit format parts without having hours part?

**Comment by arqex** [comment]
react-datetime is meant to be a date & time picker, it always return a date object as a value (a moment.js one).

When selecting a date, you can select a year, but you can't select a month without the year, the same happens to days without months.

With the time, the generalization is the same, a minute has no sense for the library if it's not inside an hour.
