### ISSUE TITLE
onBlur is not updating latest value for the first blur action

### ISSUE THREAD

**Issue by sushanthdv** [arqex/react-datetime#659]
Expected Behaviour :
If i enter any invalid string in input , onBlur input should clear.

Problem am facing:
1) Typing a sytring like 'abcd' input and onBlur setting this.state.date to empty string . 
2) But input is not updating.
3)When i comeback and change the existing string 'abcd' to 'abcde' and onBlur working fine

My Code looks like:

`<DateTime
        value={this.state.date}
        isValidDate={this.valid}
        inputProps={{
          placeholder: DATE_FORMAT,
          ref: this.datePickerRef,
          className: `ctui-form-control ${this.state.valid ? '' : 'invalid'}`,
         onBlur: () => this.setValidDate(),
        }}
        onChange={this.validateDate}
        dateFormat="YYYY-MM-DD"
        timeFormat={false}
        locale={moment.locale()}
        input={true}
        closeOnSelect
      />`

`setValidDate() {
    const datePicker = this.datePickerRef && this.datePickerRef.current;
    let isInvalidClass: boolean = !this.state.valid
    if (isInvalidClass && datePicker) {
      datePicker.value = '';
      this.setState({ date: datePicker.value, valid: true }, () =>
        this.props.setDate(datePicker.value)
      );
    }
  }`

**Comment by sushanthdv** [comment]
My componentWillReceiveProps looks like this :

`componentWillReceiveProps(prevProps: Props) {
    if (this.props.setDate !== prevProps.setDate) {
      this.setState({
        maxDate: prevProps.maxDate,
        minDate: prevProps.minDate,
        date: prevProps.currentValue || '',
      });
    }`

**Comment by KAloraifi** [comment]
I'm having a similar issue with regards to `onBlur`. It's not updating the input `value` after the first insertion. the value updates and works if I remove the `onBlur` handler.

**Comment by arqex** [comment]
In the new version 3 `onBlur` has been renamed to `onClose`. It's a better name, since it's triggered when the calendar picker is closed.

If anybody is interested in the real `onBlur` method of the `input`, it's possible to use the prop `inputProps` to pass the listener direct to the input:

```jsx
<Datetime inputProps{{onBlur: e => console.log('Blur!!!', e)}} />
```
