### ISSUE TITLE
Weirdly InputProps disabled is not working for me.

### ISSUE THREAD

**Issue by gaurav-quasar** [arqex/react-datetime#667]
I am try to disable the datetime input in certain scenarios but somehow i am not able to do this.
I saw (working) examples but they were using version 2.8.6.

I am using 2.16.3

Below is the screenshot for the same.
<img width="1097" alt="Screenshot 2019-11-21 at 4 29 36 PM" src="https://user-images.githubusercontent.com/21342476/69333122-166ee380-0c7e-11ea-86a2-8591748c0d24.png">

**Comment by stevej2608** [comment]
You can use inputProps setting.

`<DateTime inputProps={{disabled: true}} />`


[arqex commented on 1 Oct 2015](https://github.com/YouCanBookMe/react-datetime/issues/22#issuecomment-144760533)

**Comment by gaurav-quasar** [comment]
@stevej2608, I used the same. In my above comment, you can see that in debugger, it shows inputProps: disabled true.

But the problem is, we still get a calendar open, even though you can't select a date in it.

As per me, ideal behaviour should be that input button shouldn't be clicked at all and calendar should not popup(even the disabled one) and this was working correctly in version 2.8.6.

You can see it in below pen, it is working correctly but react-datetime version used is older (2.8.6)

https://codepen.io/gaurav-quasar/pen/zYGjzKa

https://rawgit.com/arqex/react-datetime/master/dist/react-datetime.js

**Comment by gaurav-quasar** [comment]
Below codepen is with latest react-datetime version and this has issues:

https://codepen.io/gaurav-quasar/pen/gOpzRgp

**Comment by arqex** [comment]
Hey! Sorry for the delay!

This is fixed in v3. If the input is disabled, you can't focus it by clicking so the calendar is never open:

https://codesandbox.io/s/elastic-cori-upk3x
