### ISSUE TITLE
Using `react-datetime` css with emotion generates a console error

### ISSUE THREAD

**Issue by erezrokah** [arqex/react-datetime#668]
### I'm Submitting a

```
[x] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce
Using `react-datetime` css with emotion generates a console error.

![image](https://user-images.githubusercontent.com/26760571/69790134-96d79c00-11ca-11ea-97a7-a2bd050af9f1.png)

Use the following code to generate the error:

```
/** @jsx jsx */
import React from 'react';
import { jsx, css } from '@emotion/core';
import reactDateTimeStyles from 'react-datetime/css/react-datetime.css';
import DateTime from 'react-datetime';

export default class DateTimeComponent extends React.Component {
  render() {
    return (
      <div
        css={css`
          ${reactDateTimeStyles};
        `}
      >
        <DateTime value={new Date()} />
      </div>
    );
  }
}
```

### Expected Results
No error is logged

### Actual Results
Error is logged

### Minimal Reproduction of the Problem
1. [Setup a react app](https://github.com/facebook/create-react-app).
2. [Add emotion](https://emotion.sh/docs/install)
3. Add a react component using the above code.
4. Load the react app in the browser see the error in the console.

**Comment by arqex** [comment]
Thanks for the feedback @erezrokah !

I'll update it for the next version of react-datetime that it's coming :)

**Comment by arqex** [comment]
The issue has already been fixed in the last version, but unfortunately this PR didn't make it into the result.

**Comment by erezrokah** [comment]
Thank you for the follow up!
