### ISSUE TITLE
Time zone does not apply. It's a very serious problem. I have to fix it, but it doesn't work. What should I do?

### ISSUE THREAD

**Issue by passion0470** [arqex/react-datetime#675]
Time zone does not apply.
It's a very serious problem. I have to fix it, but it doesn't work.
What should I do?

`import moment from 'moment';
``import timezone from 'moment-timezone';
`
`moment([
                        data.map.detail.end.substring(0, 4), 
                        data.map.detail.end.substring(5, 7)-1, 
                        data.map.detail.end.substring(8, 10),
                        data.map.detail.end.substring(11, 13),
                        data.map.detail.end.substring(14, 16)
 ]).tz("Asia/Seoul")`

`<DateTimeField className="cal-right-date btn-select-time c-blue" onChange={e => onChangeDateTime(e, 'post.end')} value={post.end !== '' &&  post.end} name="post.end" title="" closeOnSelect={true} dateFormat={'YYYY-MM-DD'} timeFormat={post.alldayYn === 'Y' ? false : 'HH:mm'} displayTimeZone={'Asia/Seoul'} />
`

**Comment by jaagupku** [comment]
If you only need to display one time zone, you could import locale with that time zone.
It then sets date and time formats for that locale.
For example:
```
import DateTime from 'react-datetime';
import 'moment/locale/ko';

...

<DateTimeField 
    className="cal-right-date btn-select-time c-blue"
    onChange={e => onChangeDateTime(e, 'post.end')}
    value={post.end !== '' && post.end}
    name="post.end"
    title=""
    closeOnSelect={true}
    dateFormat={'YYYY-MM-DD'}
    timeFormat={post.alldayYn === 'Y' ? false : 'HH:mm'}
/>


```
