### ISSUE TITLE
[v3] FileCasePathsPlugin having issues with this repo

### ISSUE THREAD

**Issue by brandon-pereira** [arqex/react-datetime#680]
### I'm Submitting a ...
```
[ X] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce
This packages breaks when used with https://www.npmjs.com/package/case-sensitive-paths-webpack-plugin because the webpack externals is set to require react from React instead of react.

### Expected Results
Imports `require("React")` become "require("react")"

### Actual Results
Imports `require("React")` present 

### Minimal Reproduction of the Problem
Build the project, see the `dist/react-datetime.cjs.js` file and search for `require('React`);`

**Comment by arqex** [comment]
This issue is fixed in v3. Thanks for the info!
