### ISSUE TITLE
AM/PM is not localized

### ISSUE THREAD

**Issue by mandarinSh** [arqex/react-datetime#682]
### I'm Submitting a ...
```
[x ] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce
Change locale by calling ```moment.locale('ru')``` or pass it via ```locale``` property (Russian for example).
Open Calendar for choosing the time.

### Expected Results
It should be localized AM/PM there (in Russian "дня\ночи\утра\вечера").

### Actual Results
It is still AM/PM.

![image](https://user-images.githubusercontent.com/28526812/73557181-ccfef980-4461-11ea-806f-3cb5a9aa1403.png)

In the code (file ```src/TimeView```) AM\PM is hardcoded.
Please fix this. (Maybe you should replace it with ```moment``` call).

![image](https://user-images.githubusercontent.com/28526812/73557121-b789cf80-4461-11ea-8812-a28c8270b4be.png)

**Comment by mandarinSh** [comment]
Is there any update on this issue?

**Comment by arqex** [comment]
Thanks for raising the issue, and sorry for the delay! 

It's a good catch, and the code tips were really helpful too, thanks for them. I've fixed it in https://github.com/arqex/react-datetime/commit/3a557b6daebafccea2a8b0543b061cf3fca45b3c and it will be shipped in v3.0.3.

**Comment by mandarinSh** [comment]
Thank you so much @arqex ! :-)
