### ISSUE TITLE
Is it possible to have internally input formatting for specified locale for "month picker"?

### ISSUE THREAD

**Issue by pavelkuznetsov** [arqex/react-datetime#693]
### I'm Submitting a ...

```
[ ] Bug report
[ ] Feature request
[x] Support request
```
### Question
Hi, thanks for great job with react-datetime!

When I define `locale` property for `DateTime` and `dateFormat` is not specified (`dateFormat = true`) input format is calculated internally for this `locale`. Here is an example: https://codesandbox.io/s/react-datetime-sp9xd . If the button is clicked, `locale` changes and input format changes too. DateTime is doing it by itself and it's great!

But, if I need "month picker" and exactly the same behaviour I cant achive it. It seems like the only way I can configure `DateTime` to select only a year and month (and not day) is to specify `dateFormat`. But when I do it, all "the magic" with input formatting for `locale` disappears, because formatting was explicit defined.
Previous example but with `dateFormat="YYYY-MM"`: https://codesandbox.io/s/react-datetime-jon3n . Formatting is always "YYYY-MM", `locale` changing doesnt affect input formatting if `dateFormat"` is specified.
I can understand this behaviour, but maybe there is a possibility to configure `DateTime` to select only year and month and have internally calculated input formatting for selected `locale`, like in first example but just without days? (I mean, I need to have MM.YYYY for 'de' and  MM/YYYY for 'en')

**Comment by arqex** [comment]
Hey @pavelkuznetsov 

Sorry for the delay. Now in v3 there is a `updateOnView` property that does exactly what you want:

```jsx
import React from "react";
import "react-datetime/css/react-datetime.css";
import Datetime from "react-datetime";

export default function App() {
  return (
    <Datetime updateOnView="months" timeFormat={false} closeOnSelect={true} />
  );
}
```

See it working: https://codesandbox.io/s/optimistic-bartik-mnxt2
