### ISSUE TITLE
Can't resolve './locale' in ......./node_modules/moment/src/lib/locale

### ISSUE THREAD

**Issue by oasis9594** [arqex/react-datetime#697]
Getting the following error which may be due to recent changes in moment module. There is an open issue at: https://github.com/moment/moment/issues/2979

./node_modules/moment/src/lib/locale/locales.js
Module not found: Error: Can't resolve './locale' in '......./node_modules/moment/src/lib/locale'
 @ ./node_modules/moment/src/lib/locale/locales.js
 @ ./node_modules/moment/src/lib/locale/locale.js
 @ ./node_modules/moment/src/moment.js
 @ ./node_modules/react-datetime/DateTime.js

**Comment by arqex** [comment]
Thanks for raising the issue, and sorry for the delay! It's fixed as part of version 3 🙂
