### ISSUE TITLE
Can't getInstance of undefined issue

### ISSUE THREAD

**Issue by NicoCrow** [arqex/react-datetime#699]
https://github.com/YouCanBookMe/react-datetime/blob/941c78d0abd93def4e448475641a0037c09c618f/DateTime.js#L505

`ClickableWrapper` is `undefined` in the `Datetime` component (line496). 
Please move `ClickableWrapper` to the top (before `Datetime`) and generate new version.

**Comment by arqex** [comment]
Thanks for raising the issue, and sorry for the delay! It's fixed as part of version 3 🙂
