### ISSUE TITLE
react-datetime (react warning)

### ISSUE THREAD

**Issue by theouerd** [arqex/react-datetime#704]
Hello, 
I'm using react-datetime (version 2.16.3)  in my current project (react version : 16.13.1) and i'm getting the following warning on my console:

react_devtools_backend.js:6 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
***Please update the following components: DateTime***

Please, any idea about this warning.

**Comment by Oscaralsa** [comment]
I got the same problem

**Comment by devchris** [comment]
Is this project still maintained?

**Comment by arqex** [comment]
Thanks for raising the issue, and sorry for the delay! It's fixed as part of version 3 🙂
