### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by klekowskim** [arqex/react-datetime#705]
Hi @arqex 
What is the sate of the version 3? Do you need any help with finishing it and releasing?

**Comment by caleb-harrelson** [comment]
I'd also like to know about the future of the project, @arqex.

Anybody here using v3 in production? I'm wary of updating to v3 since it's still in beta and hasn't been touched in 6+ months, but we won't be able to stay on v2.16.3 much longer.

**Comment by arqex** [comment]
Sorry so much for the delay!! The project was sponsored by YouCanBook.me ( my current employer ) so I was supposed to take care of it in my working hours. Unfortunatelly there was always so much work that I wasn't never able to give react-datetime the love it deserved.

Good news are that YouCanBook.me were understanding the issue and gave the repo back to me, so I can now take care of it in my spare time again. So there we go the v3 is out!

I'm right now the only maintainer and I would be glad if more people could contribute to the project. I'm trying to define the direction of the project for v4. Any help is much appreciated!!

https://github.com/arqex/react-datetime/issues/723
