### ISSUE TITLE
Property 'moment' does not exist on type 'typeof ReactDatetimeClass'.

### ISSUE THREAD

**Issue by Pattygeek** [arqex/react-datetime#707]
let yesterday = Datetime.moment().subtract(1, "day");

I got this piece of code from the docs but I get an error, which i used as the title.

this is the versio i am using    "react-datetime": "^2.16.3",

**Comment by arqex** [comment]
Accessing `moment` through the `Datetime`  by using `Datetime.moment()`  class is not recommended.

Try to import moment separately in your file:

```js
import moment from 'moment';

let yesterday = moment().subtract(1, 'day');
```
