### ISSUE TITLE
Days of the week not coming through for Portuguese

### ISSUE THREAD

**Issue by jdoud** [arqex/react-datetime#711]
### I'm Submitting a ...

```
[x] Bug report
[ ] Feature request
[ ] Support request
```

When passing in a locale for localizaton, the days of the week are corrupted. Seems to be only happening for Portuguese.

<img width="395" alt="Calendar" src="https://user-images.githubusercontent.com/1130890/89465115-9327ec00-d73f-11ea-9f2e-bd520736a9b6.png">

**Comment by arqex** [comment]
Thanks for raising the issue! Have you tried using the latest version of moment?

**Comment by arqex** [comment]
Hey @jdoud 

Days of the week in portuguese are actually called *Segunda feira*, *Tercera feira* and so on, and that means something like *second day*, *thrid day*. So those short forms for the days of the week are actually ok for Portuguese.
