### ISSUE TITLE
v3 does not contain typescript definitions

### ISSUE THREAD

**Issue by ProIcons** [arqex/react-datetime#716]
as mentioned in the title, v3 does not contain definitions for typescript.

**Comment by arqex** [comment]
Hey @ProIcons 

the definitions are here: https://github.com/arqex/react-datetime/blob/master/src/datetime/DateTime.d.ts

aren't they been displayed properly?

**Comment by ProIcons** [comment]
I reverted back to 2.x version because there wasn't any option to disable year caching, i remember though that when i installed @types/react-datetime it was just an empty file and without it i didn't have types. I can't remember more details right now.

**Comment by zaripych** [comment]
Just FYI, here is `react-datetime` from my `node_modules` and there is no `.d.ts` files included in the package.

<img width="260" alt="image" src="https://user-images.githubusercontent.com/396623/93709277-78d78f80-fb80-11ea-87f1-bf72cecbbebe.png">

So this line in `package.json`:

```
"typings": "./src/datetime/DateTime.d.ts",
```

Would be ineffective ...

**Comment by arqex** [comment]
@zaripych good catch! We weren't exposing the `src` folder in the `files` attribute of `package.json`, so they weren't available when installing react-datetime as a dependency.

I've took the chance to move the definition file to the typings folder too. Try v3.0.2, it should be fixed there.
