### ISSUE TITLE
React-datetime version 3 breaks previous integration with Formik

### ISSUE THREAD

**Issue by knguyen0125** [arqex/react-datetime#730]
### I'm Submitting a ...

```
[x ] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce

* Create a controlled Formik Field with with React-datetime Datepicker set to Timepicker
* Clicking up arrow in hour to increment hour
* Clicking up arrow in minute to increment minute

### Expected Results

Both hour and minute should remain previous choice

### Actual Results

When clicking hour up/down arrow, the minute revert to current time
When clicking minute up/down arrow, the hour revert to current time

### Minimal Reproduction of the Problem

Reproducible example: [https://codesandbox.io/s/twilight-moon-ghpqg](https://codesandbox.io/s/twilight-moon-ghpqg)

### Other Information (e.g. stacktraces, related issues, suggestions how to fix)
 
Version 2 of React-datetime doesn't have this problem.

**Comment by arqex** [comment]
Nice catch @knguyen0125 thanks! I could reproduce it and created a PR with the fix: https://github.com/arqex/react-datetime/pull/733
