### ISSUE TITLE
[Docs] Wrong link for example gallery

### ISSUE THREAD

**Issue by setiawanjeje** [arqex/react-datetime#731]
I think this is pretty straightforward.
The link for passing props example is the one for i18n.
![image](https://user-images.githubusercontent.com/11268492/93841024-86922f80-fcbc-11ea-8ada-da0b713b77d2.png)

**Comment by arqex** [comment]
Thanks for raising the issue!

**Comment by arqex** [comment]
Closed by https://github.com/arqex/react-datetime/commit/19f3ea74d90a4331ec67868befa8c233a35687d4
