### ISSUE TITLE
Component is printing "CLICKING 2!" in console

### ISSUE THREAD

**Issue by LucasKuhlemann** [arqex/react-datetime#788]
### I'm Submitting a ...
```
[x] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce
Click the input field.

### Expected Results
Works.

### Actual Results
Works, but also prints "CLICKING 2!" in the console.

### Other Information (e.g. stacktraces, related issues, suggestions how to fix)
 
In `react-datetime/dist/react-datetime.cjs.js`, latest commit (d6e72d2 at time of writing), line 1 character 30319 is the guilty statement.

**Comment by josephmarkus** [comment]
<img width="702" alt="Screenshot 2021-06-11 at 16 37 09" src="https://user-images.githubusercontent.com/9258365/121712438-a7611600-cad3-11eb-8119-4def60907686.png">

Same here, and I can't find this `console.log` in this repository via search

**Comment by tomeczekstecc** [comment]
We are about to go for production with the amazing lib. Any chance for fix soon?

**Comment by pleunv** [comment]
This one can be closed, is solved as of 3.1.0
