### ISSUE TITLE
Make react-datetime compatible with React 17.0.2

### ISSUE THREAD

**Issue by josh-annexus** [arqex/react-datetime#792]
### I'm Submitting a ...

```
[ ] Bug report
[ ] Feature request
[x] Support request
```

### Steps to Reproduce

I'm using npm version 7 and getting the following peerDependency error:
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: [myProject]
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.5.0" from react-datetime@3.0.4
npm ERR! node_modules/react-datetime
npm ERR!   react-datetime@"^3.0.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by alejandroiglesias** [comment]
Any updates on this?

**Comment by alejandroiglesias** [comment]
@layneanderson great! Will a new release come out soon?
