### ISSUE TITLE
Change first day of the week

### ISSUE THREAD

**Issue by anandqb** [arqex/react-datetime#796]
Hi! is it possible to change the first day of the week without having to rely on locale?
The requirement is to have an option for the user to change the first day of the week so that the date picker always renders with the selected day as the first day of the week for that particular user.
it is high priority for our project.
@arqex @vahissan @onlined @kkalv

**Comment by onlined** [comment]
Not trying to be rude, but you shouldn't expect anyone to care about your project.

I don't want to work on implementing this, because it didn't get my interest. I can review it though.

**Comment by anandqb** [comment]
Thanks for the quick reply,
I just wanted to express it would be really helpful if there is some way to do this already.

**Comment by anandqb** [comment]
For anyone else having a similar problem you can set the start day of the week using moment js locale
See https://codesandbox.io/s/magical-hamilton-pgrts
Cheers!
